services:
  broadcast-box:
    image: local/broadcast-box:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP=yes
    hostname: broadcast-box
    container_name: broadcast-box
    network_mode: "host"
    privileged: true
